@server = http://localhost:4004
@auth = Authorization: Basic alice:


### Orders
# @name Orders_GET
GET {{server}}/odata/v4/orders/Orders
{{auth}}


### Orders Drafts GET
# @name Orders_Drafts_GET
GET {{server}}/odata/v4/orders/Orders?$filter=(IsActiveEntity eq false)
{{auth}}


### Orders Draft POST
# @name Orders_Draft_POST
POST {{server}}/odata/v4/orders/Orders
Content-Type: application/json
{{auth}}

{
  "orderNumber": 62.11,
  "Description": "Description-19166884",
  "createdAt": "2004-08-25T00:00:00.000Z",
  "createdBy": "createdBy.bet9g@example.com",
  "modifiedAt": "2013-04-10T00:00:00.000Z",
  "modifiedBy": "modifiedBy.bet9g@example.org"
}


### Result from POST request above
@draftID = {{Orders_Draft_POST.response.body.$.ID}}


### Orders Draft PATCH
# @name Orders_Draft_Patch
PATCH {{server}}/odata/v4/orders/Orders(ID={{draftID}},IsActiveEntity=false)
Content-Type: application/json
{{auth}}

{
  "orderNumber": 62.11,
  "Description": "Description-19166884",
  "createdAt": "2004-08-25T00:00:00.000Z",
  "createdBy": "createdBy.bet9g@example.com",
  "modifiedAt": "2013-04-10T00:00:00.000Z",
  "modifiedBy": "modifiedBy.bet9g@example.org"
}


### Orders Draft Prepare
# @name Orders_Draft_Prepare
POST {{server}}/odata/v4/orders/Orders(ID={{draftID}},IsActiveEntity=false)/AdminService.draftPrepare
Content-Type: application/json
{{auth}}

{}


### Orders Draft Activate
# @name Orders_Draft_Activate
POST {{server}}/odata/v4/orders/Orders(ID={{draftID}},IsActiveEntity=false)/AdminService.draftActivate
Content-Type: application/json
{{auth}}

{}


### createContext
# @name createContext_POST
POST {{server}}/odata/v4/orders/createContext
Content-Type: application/json
{{auth}}

{}
